FROM node:14.18-alpine

RUN npm i -g lerna

WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./
COPY packages/backend/package.json ./packages/backend/
COPY packages/shared/package.json ./packages/shared/
COPY lerna.json ./
RUN yarn install

RUN lerna bootstrap
COPY . .

RUN yarn build:shared
RUN yarn build:backend

CMD node packages/backend/dist/src/main
