version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - '8000:3000'
    depends_on:
      - db

  db:
    image: postgres:10.6-alpine
    environment:
      - POSTGRES_DB=db-pg
      - POSTGRES_USER=db-pg
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'

volumes:
  db-data: {}
